# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sci/prafulag/GitRepos/hipworks

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sci/prafulag/GitRepos/hipworks

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Runtime\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/sci/prafulag/GitRepos/hipworks && $(CMAKE_COMMAND) -E cmake_progress_start /home/sci/prafulag/GitRepos/hipworks/CMakeFiles /home/sci/prafulag/GitRepos/hipworks/tinyxml/CMakeFiles/progress.marks
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f CMakeFiles/Makefile2 tinyxml/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sci/prafulag/GitRepos/hipworks/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f CMakeFiles/Makefile2 tinyxml/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f CMakeFiles/Makefile2 tinyxml/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f CMakeFiles/Makefile2 tinyxml/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/sci/prafulag/GitRepos/hipworks && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
tinyxml/CMakeFiles/tinyxml.dir/rule:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f CMakeFiles/Makefile2 tinyxml/CMakeFiles/tinyxml.dir/rule
.PHONY : tinyxml/CMakeFiles/tinyxml.dir/rule

# Convenience name for target.
tinyxml: tinyxml/CMakeFiles/tinyxml.dir/rule
.PHONY : tinyxml

# fast build rule for target.
tinyxml/fast:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/build
.PHONY : tinyxml/fast

tinystr.o: tinystr.cpp.o
.PHONY : tinystr.o

# target to build an object file
tinystr.cpp.o:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/tinystr.cpp.o
.PHONY : tinystr.cpp.o

tinystr.i: tinystr.cpp.i
.PHONY : tinystr.i

# target to preprocess a source file
tinystr.cpp.i:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/tinystr.cpp.i
.PHONY : tinystr.cpp.i

tinystr.s: tinystr.cpp.s
.PHONY : tinystr.s

# target to generate assembly for a file
tinystr.cpp.s:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/tinystr.cpp.s
.PHONY : tinystr.cpp.s

tinyxml.o: tinyxml.cpp.o
.PHONY : tinyxml.o

# target to build an object file
tinyxml.cpp.o:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/tinyxml.cpp.o
.PHONY : tinyxml.cpp.o

tinyxml.i: tinyxml.cpp.i
.PHONY : tinyxml.i

# target to preprocess a source file
tinyxml.cpp.i:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/tinyxml.cpp.i
.PHONY : tinyxml.cpp.i

tinyxml.s: tinyxml.cpp.s
.PHONY : tinyxml.s

# target to generate assembly for a file
tinyxml.cpp.s:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/tinyxml.cpp.s
.PHONY : tinyxml.cpp.s

tinyxmlerror.o: tinyxmlerror.cpp.o
.PHONY : tinyxmlerror.o

# target to build an object file
tinyxmlerror.cpp.o:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/tinyxmlerror.cpp.o
.PHONY : tinyxmlerror.cpp.o

tinyxmlerror.i: tinyxmlerror.cpp.i
.PHONY : tinyxmlerror.i

# target to preprocess a source file
tinyxmlerror.cpp.i:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/tinyxmlerror.cpp.i
.PHONY : tinyxmlerror.cpp.i

tinyxmlerror.s: tinyxmlerror.cpp.s
.PHONY : tinyxmlerror.s

# target to generate assembly for a file
tinyxmlerror.cpp.s:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/tinyxmlerror.cpp.s
.PHONY : tinyxmlerror.cpp.s

tinyxmlparser.o: tinyxmlparser.cpp.o
.PHONY : tinyxmlparser.o

# target to build an object file
tinyxmlparser.cpp.o:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/tinyxmlparser.cpp.o
.PHONY : tinyxmlparser.cpp.o

tinyxmlparser.i: tinyxmlparser.cpp.i
.PHONY : tinyxmlparser.i

# target to preprocess a source file
tinyxmlparser.cpp.i:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/tinyxmlparser.cpp.i
.PHONY : tinyxmlparser.cpp.i

tinyxmlparser.s: tinyxmlparser.cpp.s
.PHONY : tinyxmlparser.s

# target to generate assembly for a file
tinyxmlparser.cpp.s:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/tinyxmlparser.cpp.s
.PHONY : tinyxmlparser.cpp.s

xmltest.o: xmltest.cpp.o
.PHONY : xmltest.o

# target to build an object file
xmltest.cpp.o:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/xmltest.cpp.o
.PHONY : xmltest.cpp.o

xmltest.i: xmltest.cpp.i
.PHONY : xmltest.i

# target to preprocess a source file
xmltest.cpp.i:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/xmltest.cpp.i
.PHONY : xmltest.cpp.i

xmltest.s: xmltest.cpp.s
.PHONY : xmltest.s

# target to generate assembly for a file
xmltest.cpp.s:
	cd /home/sci/prafulag/GitRepos/hipworks && $(MAKE) -f tinyxml/CMakeFiles/tinyxml.dir/build.make tinyxml/CMakeFiles/tinyxml.dir/xmltest.cpp.s
.PHONY : xmltest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... tinyxml"
	@echo "... tinystr.o"
	@echo "... tinystr.i"
	@echo "... tinystr.s"
	@echo "... tinyxml.o"
	@echo "... tinyxml.i"
	@echo "... tinyxml.s"
	@echo "... tinyxmlerror.o"
	@echo "... tinyxmlerror.i"
	@echo "... tinyxmlerror.s"
	@echo "... tinyxmlparser.o"
	@echo "... tinyxmlparser.i"
	@echo "... tinyxmlparser.s"
	@echo "... xmltest.o"
	@echo "... xmltest.i"
	@echo "... xmltest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/sci/prafulag/GitRepos/hipworks && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

