#include "PythonProject.h"

#include <Project/DeepSSMParameters.h>

namespace py = pybind11;
using namespace pybind11::literals;

using namespace shapeworks;

void define_python_project(pybind11::module_ m) {
  py::class_<DeepSSMParameters>(m, "DeepSSMParameters")
      .def(py::init<std::shared_ptr<Project>>())
      .def("save_to_project", &DeepSSMParameters::save_to_project)
      .def("get_model_mode", &DeepSSMParameters::get_model_mode)
      .def("set_model_mode", &DeepSSMParameters::set_model_mode)
      .def("get_aug_num_samples", &DeepSSMParameters::get_aug_num_samples)
      .def("set_aug_num_samples", &DeepSSMParameters::set_aug_num_samples)
      .def("get_aug_num_dims", &DeepSSMParameters::get_aug_num_dims)
      .def("set_aug_num_dims", &DeepSSMParameters::set_aug_num_dims)
      .def("get_training_num_dims", &DeepSSMParameters::get_training_num_dims)
      .def("set_training_num_dims", &DeepSSMParameters::set_training_num_dims)
      .def("get_aug_percent_variability", &DeepSSMParameters::get_aug_percent_variability)
      .def("set_aug_percent_variability", &DeepSSMParameters::set_aug_percent_variability)
      .def("get_aug_sampler_type", &DeepSSMParameters::get_aug_sampler_type)
      .def("set_aug_sampler_type", &DeepSSMParameters::set_aug_sampler_type)
      .def("get_training_epochs", &DeepSSMParameters::get_training_epochs)
      .def("set_training_epochs", &DeepSSMParameters::set_training_epochs)
      .def("get_training_learning_rate", &DeepSSMParameters::get_training_learning_rate)
      .def("set_training_learning_rate", &DeepSSMParameters::set_training_learning_rate)
      .def("get_training_decay_learning_rate", &DeepSSMParameters::get_training_decay_learning_rate)
      .def("set_training_decay_learning_rate", &DeepSSMParameters::set_training_decay_learning_rate)
      .def("get_training_fine_tuning", &DeepSSMParameters::get_training_fine_tuning)
      .def("set_training_fine_tuning", &DeepSSMParameters::set_training_fine_tuning)
      .def("get_training_fine_tuning_epochs", &DeepSSMParameters::get_training_fine_tuning_epochs)
      .def("set_training_fine_tuning_epochs", &DeepSSMParameters::set_training_fine_tuning_epochs)
      .def("get_training_fine_tuning_learning_rate", &DeepSSMParameters::get_training_fine_tuning_learning_rate)
      .def("set_training_fine_tuning_learning_rate", &DeepSSMParameters::set_training_fine_tuning_learning_rate)
      .def("get_training_batch_size", &DeepSSMParameters::get_training_batch_size)
      .def("set_training_batch_size", &DeepSSMParameters::set_training_batch_size)
      .def("get_training_split", &DeepSSMParameters::get_training_split)
      .def("set_training_split", &DeepSSMParameters::set_training_split)
      .def("get_validation_split", &DeepSSMParameters::get_validation_split)
      .def("set_validation_split", &DeepSSMParameters::set_validation_split)
      .def("get_testing_split", &DeepSSMParameters::get_testing_split)
      .def("set_testing_split", &DeepSSMParameters::set_testing_split)
      .def("get_prep_step_complete", &DeepSSMParameters::get_prep_step_complete)
      .def("set_prep_step_complete", &DeepSSMParameters::set_prep_step_complete)
      .def("get_prep_stage", &DeepSSMParameters::get_prep_stage)
      .def("set_prep_stage", &DeepSSMParameters::set_prep_stage)
      .def("get_aug_step_complete", &DeepSSMParameters::get_aug_step_complete)
      .def("set_aug_step_complete", &DeepSSMParameters::set_aug_step_complete)
      .def("get_aug_message", &DeepSSMParameters::get_aug_message)
      .def("set_aug_message", &DeepSSMParameters::set_aug_message)
      .def("get_training_step_complete", &DeepSSMParameters::get_training_step_complete)
      .def("set_training_step_complete", &DeepSSMParameters::set_training_step_complete)
      .def("get_training_message", &DeepSSMParameters::get_training_message)
      .def("set_training_message", &DeepSSMParameters::set_training_message)
      .def("get_spacing", &DeepSSMParameters::get_spacing)
      .def("set_spacing", &DeepSSMParameters::set_spacing)
      .def("get_loss_function", &DeepSSMParameters::get_loss_function)
      .def("set_loss_function", &DeepSSMParameters::set_loss_function)
      .def("get_tl_net_enabled", &DeepSSMParameters::get_tl_net_enabled)
      .def("set_tl_net_enabled", &DeepSSMParameters::set_tl_net_enabled)
      .def("get_tl_net_ae_epochs", &DeepSSMParameters::get_tl_net_ae_epochs)
      .def("set_tl_net_ae_epochs", &DeepSSMParameters::set_tl_net_ae_epochs)
      .def("get_tl_net_tf_epochs", &DeepSSMParameters::get_tl_net_tf_epochs)
      .def("set_tl_net_tf_epochs", &DeepSSMParameters::set_tl_net_tf_epochs)
      .def("get_tl_net_joint_epochs", &DeepSSMParameters::get_tl_net_joint_epochs)
      .def("set_tl_net_joint_epochs", &DeepSSMParameters::set_tl_net_joint_epochs)
      .def("get_tl_net_alpha", &DeepSSMParameters::get_tl_net_alpha)
      .def("set_tl_net_alpha", &DeepSSMParameters::set_tl_net_alpha)
      .def("get_tl_net_a_ae", &DeepSSMParameters::get_tl_net_a_ae)
      .def("set_tl_net_a_ae", &DeepSSMParameters::set_tl_net_a_ae)
      .def("get_tl_net_c_ae", &DeepSSMParameters::get_tl_net_c_ae)
      .def("set_tl_net_c_ae", &DeepSSMParameters::set_tl_net_c_ae)
      .def("get_tl_net_a_lat", &DeepSSMParameters::get_tl_net_a_lat)
      .def("set_tl_net_a_lat", &DeepSSMParameters::set_tl_net_a_lat)
      .def("get_tl_net_c_lat", &DeepSSMParameters::get_tl_net_c_lat)
      .def("set_tl_net_c_lat", &DeepSSMParameters::set_tl_net_c_lat)
      .def("restore_split_defaults", &DeepSSMParameters::restore_split_defaults)
      .def("restore_augmentation_defaults", &DeepSSMParameters::restore_augmentation_defaults)
      .def("restore_training_defaults", &DeepSSMParameters::restore_training_defaults)
      .def("restore_defaults", &DeepSSMParameters::restore_defaults);
}
