name: Linux Build Test

on:
  workflow_dispatch:
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:

    runs-on: ubuntu-latest
    container: akenmorris/ubuntu-build-box-sw65
    
    steps:

    - name: Conda info
      run: conda info

    - name: Check space1
      run: df -h

    - name: Free some space 
      run: cd /__t ; rm -rf CodeQL go
      
    - name: Check space2
      run: df -h
      
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Workaround for permission issue
      run: git config --global --add safe.directory /__w/ShapeWorks/ShapeWorks

    - name: Check space3
      run: df -h

    - name: Restore Caches
      shell: bash -l {0}
      run: .github/workflows/restore_caches.sh

    - name: Conda Installs
      shell: bash -l {0}
      run: .github/workflows/gha_conda.sh

    - name: try import vtk
      shell: bash -l {0}
      run: conda activate shapeworks && python -c "import vtk"

    - name: Build Dependencies
      shell: bash -l {0}
      run: .github/workflows/gha_deps.sh

    - name: Check space4
      run: df -h

    - name: cmake
      shell: bash -l {0}
      run: conda activate shapeworks && mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS=-g -DITK_DIR=$HOME/install/lib/cmake/ITK-5.2 -DVTK_DIR=$HOME/install/lib/cmake/vtk-9.1 -DXLNT_DIR=$HOME/install -DLIBIGL_DIR=$HOME/install -DOpenVDB_DIR=$HOME/install/lib/cmake/OpenVDB -DGEOMETRYCENTRAL_DIR=$HOME/install -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBuild_Studio=ON -DJKQTCommonSharedLib_DIR=$HOME/install/lib/cmake/JKQTCommonSharedLib -DJKQTMathTextSharedLib_DIR=$HOME/install/lib/cmake/JKQTMathTextSharedLib -DJKQTPlotterSharedLib_DIR=$HOME/install/lib/cmake/JKQTPlotterSharedLib -DACVD_DIR=$HOME/install -DCMAKE_PREFIX_PATH=${CONDA_PREFIX} -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/shapeworks-install -DUSE_ORIGIN_RPATH=ON -DGA_MEASUREMENT_ID=$GA_MEASUREMENT_ID ..

    - name: Check space5
      run: df -h

    - name: make
      shell: bash -l {0}
      run: conda activate shapeworks && cd build && make -j4

    - name: Check space6
      run: df -h

    - name: Du
      run: cd / ; du -sh * || true

    - name: make install
      shell: bash -l {0}
      run: conda activate shapeworks && cd build && make install
      
    - name: Build Binary Package
      shell: bash -l {0}
      env:
        PR_NUMBER: ${{ github.event.number }}
      run: conda activate shapeworks && source ./devenv.sh ./build/bin && PATH=$HOME:$PATH ./Support/package.sh tag ${GITHUB_WORKSPACE}/shapeworks-install $HOME/install

    - name: Download test data
      shell: bash -l {0}
      run: .github/workflows/download_test_data.sh
      
    - name: make test
      shell: bash -l {0}
      run: conda activate shapeworks && source ./devenv.sh ./build/bin && cd build && ctest -VV

    

      
